# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetinfo', '0002_auto_20160624_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffet',
            name='child_price',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='hrs_closing',
            field=models.TimeField(help_text='Please use the following format: <em>HH:MM:SS</em>. 24-hour format.'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='hrs_opening',
            field=models.TimeField(help_text='Please use the following format: <em>HH:MM:SS</em>. 24-hour format'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='location',
            field=models.CharField(choices=[('Jurong East', 'Jurong East'), ('Bukit Batok', 'Bukit Batok'), ('Bukit Gombak', 'Bukit Gombak'), ('Choa Chu Kang', 'Choa Chu Kang')], max_length=200),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='price',
            field=models.FloatField(help_text='in S$'),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='rating',
            field=models.FloatField(help_text='0 to 1, where 0 is no stars and 1 is 5 stars'),
        ),
    ]
