# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buffetinfo', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='approved_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='buffet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='buffetinfo.Buffet'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.CharField(max_length=200),
        ),
    ]
