# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buffetinfo', '0005_auto_20160626_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pub_date',
        ),
    ]
