# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetinfo', '0008_auto_20160627_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffet',
            name='phone_number',
            field=models.CharField(default=61234567, max_length=8),
            preserve_default=False,
        ),
    ]
