# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetinfo', '0009_buffet_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffet',
            name='cuisine_type',
            field=models.CharField(choices=[('International', 'International'), ('Korean BBQ', 'Koran BBQ'), ('Japanese Steamboat', 'Japanese Steamboat'), ('Vegeterian', 'Vegeterian')], max_length=200, null=True),
        ),
    ]
