# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetinfo', '0010_buffet_cuisine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffet',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='child_price',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='cuisine_type',
            field=models.CharField(choices=[('International', 'International'), ('Korean BBQ', 'Koran BBQ'), ('Japanese Steamboat', 'Japanese Steamboat'), ('Vegeterian', 'Vegeterian')], max_length=200),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='price',
            field=models.CharField(help_text='in S$', max_length=100),
        ),
    ]
