# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetinfo', '0012_auto_20160627_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buffet',
            name='child_price',
        ),
        migrations.RemoveField(
            model_name='buffet',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='buffet',
            name='price',
        ),
        migrations.AddField(
            model_name='buffet',
            name='phone_number1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='phone_number2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekday_adult_breakfast_price',
            field=models.FloatField(blank=True, help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekday_adult_dinner_price',
            field=models.FloatField(help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekday_adult_hightea_price',
            field=models.FloatField(blank=True, help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekday_adult_lunch_price',
            field=models.FloatField(help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekday_child_breakfast_price',
            field=models.FloatField(blank=True, help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekday_child_dinner_price',
            field=models.FloatField(blank=True, help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekday_child_hightea_price',
            field=models.FloatField(blank=True, help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekday_child_lunch_price',
            field=models.FloatField(blank=True, help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekend_adult_breakfast_price',
            field=models.FloatField(blank=True, help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekend_adult_dinner_price',
            field=models.FloatField(help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekend_adult_hightea_price',
            field=models.FloatField(blank=True, help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekend_adult_lunch_price',
            field=models.FloatField(help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekend_child_breakfast_price',
            field=models.FloatField(blank=True, help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekend_child_dinner_price',
            field=models.FloatField(blank=True, help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekend_child_hightea_price',
            field=models.FloatField(blank=True, help_text='in S$', null=True),
        ),
        migrations.AddField(
            model_name='buffet',
            name='weekend_child_lunch_price',
            field=models.FloatField(blank=True, help_text='in S$', null=True),
        ),
    ]
