# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buffetinfo', '0013_auto_20160628_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buffet',
            old_name='phone_number1',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='buffet',
            name='phone_number2',
        ),
    ]
