# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetinfo', '0014_auto_20160628_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffet',
            name='cuisine_type',
            field=models.CharField(choices=[('International', 'International'), ('Korean BBQ', 'Korean BBQ'), ('Japanese Steamboat', 'Japanese Steamboat'), ('Vegeterian', 'Vegeterian')], max_length=200),
        ),
    ]
