# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buffetinfo', '0018_auto_20160729_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buffetinfo.Review'),
        ),
    ]
