# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetinfo', '0019_auto_20160729_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default=None, upload_to='reviews'),
            preserve_default=False,
        ),
    ]
