# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffetinfo', '0020_auto_20160729_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffet',
            name='hrs_closing',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='hrs_opening',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekday_adult_breakfast_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekday_adult_dinner_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekday_adult_hightea_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekday_adult_lunch_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekday_child_breakfast_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekday_child_dinner_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekday_child_hightea_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekday_child_lunch_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekend_adult_breakfast_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekend_adult_dinner_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekend_adult_hightea_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekend_adult_lunch_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekend_child_breakfast_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekend_child_dinner_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekend_child_hightea_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffet',
            name='weekend_child_lunch_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
